### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by cgrossde** [lynshi/CubeOfLED#1]
I just found your repository and all the amazing work you put into the animations :) When I wrote the original code I already put so much work into building the cube that the animations kinda fell short.
But you are awesome! I really like your animations :+1: 

I merged your codebase with mine and uploaded it on my cube and after some small changes it worked!
- Would you mind if I integrate your animations in my [repository](https://github.com/cgrossde/RGB-Led-Cube)? Of course with mentioning that you made those animations and a link to this repository.
- What kind of cube did you build? And what inspired you to build one?
- Do you have some blog/website with some more information on your project?

**Comment by lynshi** [comment]
Hello, thank you for stopping by to take a look at our project! The code you wrote was really helpful because it made it easy for us to control the cube so we could spend more time on the animations.

We built a 4x4x4 RGB LED cube, and we were inspired to do so because our engineering teacher (we go to the Middlesex County Academy for Science, Mathematics, and Engineering Technologies in New Jersey) showed us some videos of LED cubes and offered extra credit to his students if they built one. My friend and I thought this was really cool and of course extra credit is great as well so we decided to begin the project. After completing the cube we made a video to show our class which can be found here: [https://drive.google.com/file/d/0B6kFJc_P1jYYQ1VSck5pY3d0aDA/view?usp=sharing](url).

Please feel free to add our animations to your repository; after all, we owe half of our program to your original code.
